name: Project improvement
description: Suggest an improvement to a project brief
body:
  - type: input
    id: project
    attributes:
      label: Project
    validations:
      required: true
  - type: textarea
    id: improvement
    attributes:
      label: Improvement
    validations:
      required: true
